import { useEffect, useState } from "react";
import { DescriptionOutlined, DownloadOutlined, EmojiEventsOutlined } from "@mui/icons-material";
import { apiRequest } from "../../lib/api";
import { isProductBucketAllowed } from "../../lib/productMode";
import { notifySuccess } from "../../lib/notify";
import { PageHeader } from "./components/PageHeader";
import { StatusChip } from "./components/StatusChip";
import { useParentPortal } from "./ParentPortalContext";
import { PARENT_BORDER, PARENT_PRIMARY, PARENT_PRIMARY_SUBTLE } from "./ParentPortalLayout";

interface CertificateRow {
  id: string;
  name: string;
  serialNumber?: string | null;
  createdAt: string;
}

interface DocumentsResponse {
  certificates?: CertificateRow[];
  documents?: Array<{ id: string; name: string; fileUrl: string | null; createdAt: string }>;
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

export function ParentCertificatesPage() {
  const { activeChild, portalChild, accessToken, productMode } = useParentPortal();
  const showCms = isProductBucketAllowed(productMode, "CMS");
  const studentId = portalChild?.student.id;
  const [certificates, setCertificates] = useState<CertificateRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!showCms || !studentId) {
      setLoading(false);
      setCertificates([]);
      return;
    }
    setLoading(true);
    setError("");
    apiRequest<DocumentsResponse>(`/portal/children/${studentId}/documents`, accessToken)
      .then((data) => setCertificates(data.certificates ?? []))
      .catch((cause: unknown) => {
        setError(cause instanceof Error ? cause.message : "Unable to load certificates");
      })
      .finally(() => setLoading(false));
  }, [accessToken, studentId, showCms]);

  if (!showCms) {
    return (
      <div className="rounded-2xl border border-[#E5E7EB] bg-white px-6 py-12 text-center text-[14px] text-[#6B7280]">
        Certificates are available when the school has CMS documents enabled.
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        title="Certificates"
        subtitle={`Issued certificates and documents for ${activeChild.name}.`}
      />

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {[
          {
            title: "Bonafide / School docs",
            description: "Issued school certificates appear in the list below when ready.",
            icon: DescriptionOutlined,
          },
          {
            title: "Achievement",
            description: "Recognition certificates generated by the school office.",
            icon: EmojiEventsOutlined,
          },
          {
            title: "Print / Download",
            description: "Open a ready certificate to print or save as PDF.",
            icon: DownloadOutlined,
          },
        ].map((card) => (
          <div
            key={card.title}
            className="rounded-[20px] border bg-white p-4 shadow-[0_4px_18px_rgba(28,27,60,0.04)]"
            style={{ borderColor: PARENT_BORDER }}
          >
            <span
              className="grid size-10 place-items-center rounded-xl"
              style={{ background: PARENT_PRIMARY_SUBTLE, color: PARENT_PRIMARY }}
            >
              <card.icon sx={{ fontSize: 20 }} />
            </span>
            <p className="mt-3 text-[14px] font-bold text-[#1A1A2E]">{card.title}</p>
            <p className="mt-1 text-[12px] text-[#6B7280]">{card.description}</p>
          </div>
        ))}
      </div>

      <section
        className="overflow-hidden rounded-[20px] border bg-white shadow-[0_4px_18px_rgba(28,27,60,0.04)]"
        style={{ borderColor: PARENT_BORDER }}
      >
        <div className="border-b px-5 py-4" style={{ borderColor: PARENT_BORDER }}>
          <h2 className="text-[15px] font-bold text-[#1A1A2E]">Issued certificates</h2>
        </div>
        {loading ? (
          <p className="px-5 py-10 text-center text-[13px] text-[#6B7280]">Loading…</p>
        ) : error ? (
          <p className="px-5 py-6 text-[13px] text-red-700">{error}</p>
        ) : certificates.length === 0 ? (
          <p className="px-5 py-10 text-center text-[13px] text-[#6B7280]">
            No certificates have been issued yet. Request new ones through the school office.
          </p>
        ) : (
          <ul className="divide-y" style={{ borderColor: PARENT_BORDER }}>
            {certificates.map((cert) => (
              <li key={cert.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4">
                <div>
                  <p className="text-[14px] font-bold text-[#1A1A2E]">{cert.name}</p>
                  <p className="text-[12px] text-[#6B7280]">
                    {cert.serialNumber ? `Serial ${cert.serialNumber} · ` : ""}
                    Issued {formatDate(cert.createdAt)}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <StatusChip label="Ready" tone="green" />
                  <a
                    href={`#/print/documents/${cert.id}`}
                    className="inline-flex items-center gap-1 rounded-xl px-3 py-1.5 text-[12px] font-bold text-white"
                    style={{ background: PARENT_PRIMARY }}
                    onClick={() => notifySuccess("Opening certificate print view")}
                  >
                    <DownloadOutlined sx={{ fontSize: 16 }} /> Open
                  </a>
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
