import { useEffect, useState, type FormEvent } from "react";
import { Navigate } from "react-router-dom";
import { apiRequest, assetUrl } from "../../lib/api";
import { isProductBucketAllowed } from "../../lib/productMode";
import { notifyError, notifySuccess } from "../../lib/notify";
import { usePortal } from "./PortalContext";

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:4000/api/v1";

interface PortalDocument {
  id: string;
  name: string;
  fileUrl: string;
  folder: string;
  folderId?: string;
  createdAt: string;
}

interface PortalCertificate {
  id: string;
  name: string;
  createdAt: string;
  serialNumber: string | null;
}

interface DocumentsResponse {
  documents: PortalDocument[];
  certificates: PortalCertificate[];
  folders: Array<{ id: string; name: string }>;
}

export function PortalDocumentsPage() {
  const { accessToken, child, productMode, basePath } = usePortal();
  const [data, setData] = useState<DocumentsResponse | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [folderId, setFolderId] = useState("");
  const [name, setName] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const showCms = isProductBucketAllowed(productMode, "CMS");

  function reload() {
    if (!showCms || !child) {
      setLoading(false);
      return;
    }
    setLoading(true);
    apiRequest<DocumentsResponse>(`/portal/children/${child.student.id}/documents`, accessToken)
      .then((next) => {
        setData(next);
        if (!folderId && next?.folders?.[0]) setFolderId(next.folders[0].id);
      })
      .catch((cause: unknown) => {
        setError(cause instanceof Error ? cause.message : "Unable to load documents");
      })
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accessToken, child?.student.id, showCms]);

  async function upload(event: FormEvent) {
    event.preventDefault();
    if (!child || !folderId || !file) {
      notifyError("Select a folder and file");
      return;
    }
    setBusy(true);
    try {
      const form = new FormData();
      form.append("file", file);
      form.append("folderId", folderId);
      if (name.trim()) form.append("name", name.trim());
      const response = await fetch(`${API_URL}/portal/children/${child.student.id}/documents`, {
        method: "POST",
        headers: { Authorization: `Bearer ${accessToken}` },
        body: form,
      });
      if (!response.ok) {
        const text = await response.text();
        let message = `Upload failed (${response.status})`;
        try {
          message =
            (JSON.parse(text) as { error?: { message?: string } }).error?.message ?? message;
        } catch {
          /* ignore */
        }
        throw new Error(message);
      }
      notifySuccess("Document uploaded");
      setFile(null);
      setName("");
      reload();
    } catch (cause) {
      notifyError(cause instanceof Error ? cause.message : "Unable to upload document");
    } finally {
      setBusy(false);
    }
  }

  if (!showCms) {
    return <Navigate to={basePath} replace />;
  }

  if (!child) {
    return <p className="text-sm text-slate-500">No student profile linked.</p>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">Documents</h1>
        <p className="mt-1 text-sm text-slate-500">
          View and upload documents. Certificates generated by the school appear below.
        </p>
      </div>

      {error && <p className="alert-error">{error}</p>}

      <form className="card grid gap-3 p-5 md:grid-cols-4" onSubmit={upload}>
        <label className="text-sm md:col-span-1">
          Folder
          <select
            className="input mt-1 w-full"
            required
            value={folderId}
            onChange={(e) => setFolderId(e.target.value)}
          >
            <option value="">Select folder</option>
            {(data?.folders ?? []).map((folder) => (
              <option key={folder.id} value={folder.id}>
                {folder.name}
              </option>
            ))}
          </select>
        </label>
        <label className="text-sm md:col-span-1">
          Name
          <input
            className="input mt-1 w-full"
            placeholder="Optional"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
        </label>
        <label className="text-sm md:col-span-1">
          File
          <input
            className="input mt-1 w-full"
            type="file"
            accept=".pdf,.jpg,.jpeg,.png,.webp,.gif,.doc,.docx,.xls,.xlsx"
            required
            onChange={(e) => setFile(e.target.files?.[0] ?? null)}
          />
        </label>
        <div className="flex items-end">
          <button className="button-primary w-full" disabled={busy || !(data?.folders?.length)}>
            {busy ? "Uploading…" : "Upload"}
          </button>
        </div>
        {!data?.folders?.length && !loading ? (
          <p className="md:col-span-4 text-sm text-amber-700">
            No document folders are configured yet. Ask the school office to create them.
          </p>
        ) : null}
      </form>

      {loading ? (
        <p className="text-sm text-slate-500">Loading documents…</p>
      ) : (
        <>
          <section className="card overflow-hidden">
            <div className="border-b border-slate-100 px-5 py-4 font-semibold">Documents</div>
            {!data?.documents.length ? (
              <p className="p-5 text-sm text-slate-500">No documents uploaded.</p>
            ) : (
              <div className="divide-y divide-slate-100">
                {data.documents.map((doc) => (
                  <div
                    className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-sm"
                    key={doc.id}
                  >
                    <div>
                      <p className="font-medium">{doc.name}</p>
                      <p className="text-xs text-slate-500">
                        {doc.folder} · {new Date(doc.createdAt).toLocaleDateString()}
                      </p>
                    </div>
                    <a
                      className="text-sm font-semibold text-indigo-700"
                      href={assetUrl(doc.fileUrl)}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Open
                    </a>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section className="card overflow-hidden">
            <div className="border-b border-slate-100 px-5 py-4 font-semibold">Certificates</div>
            {!data?.certificates.length ? (
              <p className="p-5 text-sm text-slate-500">No certificates generated.</p>
            ) : (
              <div className="divide-y divide-slate-100">
                {data.certificates.map((cert) => (
                  <div className="px-5 py-3 text-sm" key={cert.id}>
                    <p className="font-medium">{cert.name}</p>
                    <p className="text-xs text-slate-500">
                      {cert.serialNumber ? `Serial ${cert.serialNumber} · ` : ""}
                      {new Date(cert.createdAt).toLocaleDateString()}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </section>
        </>
      )}
    </div>
  );
}
